defaults: &defaults
  sessions:
    default:
      database: roguesim_development
      hosts:
        - localhost:27017

development:
  <<: *defaults
  autocreate_indexes: true
  sessions:
    default:
      database: roguesim_development
      hosts:
        - localhost:27017

test:
  <<: *defaults
  sessions:
    default:
      database: roguesim_test
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  <<: *defaults
  sessions:
    default:
      database: roguesim_production
      hosts:
        - localhost:27017
